name: CI


on:
  push:
    branches: [ main  ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Build
        run: |
          npm ci
          npm run build --if-present
          npm run test
    
    
    
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            mateusmotaa/conversao-temperatura:latest
            mateusmotaa/conversao-temperatura:${{ github.run_number }}
      




